### PR TITLE
React test

### PR DESCRIPTION
**Pull request by Caren-Koroeny**
In this branch of the project, we have implemented tests for calculate.js, operate.js, display.js and calculator.js files with snapshot and jest tests

### CODE REVIEW

**Comment by binhussen** [comment]
@Caren-Koroeny annd @Divinity-dev would you update the pr descrption

**Comment by Divinity-dev** [comment]
Noted

Sent from Yahoo Mail on Android 
 
  On Wed, Mar 1, 2023 at 5:56 PM, Mohammed ***@***.***> wrote:   


@Caren-Koroeny annd @Divinity-dev would you update the pr descrption

**Review by binhussen — CHANGES_REQUESTED** [review]
Hi @Caren-Koroeny and @Divinity-dev , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that PR description is not describing what have you done in this this PR(Milestone), Please update your PR Description :+1: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by tufoinnkuo10 — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi @Caren-Koroeny 

Your project is complete! Great job for nailing it right on the first attempt 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- operate.js module covered
- calculate.js well tested
- work presented proffesionaly
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

tufoin

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Divinity-dev** [comment]
Thank you.

Sent from Yahoo Mail on Android 
 
  On Wed, Mar 1, 2023 at 9:06 PM, ***@***.***> wrote:   


@tufoinnkuo10 approved this pull request.

Status: Approved ✔️
 
Hi @Caren-Koroeny

Your project is complete! Great job for nailing it right on the first attempt 🥇 . There is nothing else to say other than... it's time to merge it 🍾 🚢  . Congratulations! 🎉 💯 🌟
 
Good Points 👍
    
   - Descriptive Pull Request
   - operate.js module covered
   - calculate.js well tested
   - work presented proffesionaly
   - No linter errors

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the Code reviews limits policy you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using this form.

**Pull request merged**
